name: gomodctl
on: 
  push:
    branches:
      - "!*"
    tags:
    - "v*.*.*"

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@master

    - name: Set up Go (1.13)
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Linter
      run: |
        docker run --rm -v $(pwd):/data cytopia/golint -set_exit_status=1 ./...

    - name: Test & Publish
      run: |
        go test -v -race -coverprofile=coverage.txt -covermode=atomic -tags=integration ./...
        # -s used to enable search in specified directory
        bash <(curl -s https://codecov.io/bash) -s .
        cat coverage.txt

    - name: Build
      run: |        
        make build

    - name: goreleaser
      uses: goreleaser/goreleaser-action@master
      with:
        args: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}